'use strict';

// ─────────────────────────────────────────────────────────────────────────────
// Tests for the results-screen viewport coverage assertion (TE-RES-001)
//
// The P0 pattern: results screen renders with position:static instead of
// position:fixed, causing CDN body flex-row layout to push #results-screen
// off-viewport (observed: rectTop=144.5px, width=208px across multiple builds).
//
// GEN-UX-001 shipped to gen prompts (position:fixed; inset:0; z-index:100)
// but the T1 static validator cannot catch this — computed styles require
// browser rendering. These tests validate the assertion logic by simulating
// the page.evaluate() return shape and verifying pass/fail conditions.
//
// The actual checkResultsScreenViewport() helper is injected into the shared
// Playwright boilerplate in lib/pipeline-test-gen.js and runs inside every
// game-flow spec file generated by the pipeline.
// ─────────────────────────────────────────────────────────────────────────────

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');

// ─── Replicate the assertion logic from checkResultsScreenViewport() ─────────
//
// This mirrors the page.evaluate() return shape and the assertion condition
// exactly as defined in the boilerplate in lib/pipeline-test-gen.js.
// Any change to one must be reflected in the other.

function assertResultsViewportCoverage(coverageCheck) {
  if (!coverageCheck.found) {
    // Results element not found — skip (game may not have a dedicated results element)
    return { skipped: true };
  }
  if (coverageCheck.skipped) {
    // Element exists but is not visible yet (display:none or zero-size) — skip assertion
    return { skipped: true };
  }
  // TE-RES-002: coversViewport now requires rectTop <= 10 (rectTop guard).
  // A position:relative element may have height >= innerHeight but be scrolled below the fold
  // (rectTop=200px) — the button at the bottom would be off-screen. The guard prevents that
  // false-pass. Mirrors the coversViewport computation in lib/pipeline-test-gen.js page.evaluate().
  const passes = coverageCheck.position === 'fixed' || coverageCheck.coversViewport;
  return {
    skipped: false,
    passes,
    message: passes
      ? null
      : `Results screen must be position:fixed or cover full viewport. Got: position=${coverageCheck.position}, top=${coverageCheck.rectTop}px, height=${coverageCheck.rectHeight}px, coversViewport=${coverageCheck.coversViewport}`,
  };
}

// ─── page.evaluate() return shape validator ───────────────────────────────────
//
// Validates the shape of what page.evaluate() returns. In real tests, this
// runs inside the browser via Playwright. Here we construct synthetic payloads
// to confirm the assertion logic classifies them correctly.

describe('TE-RES-001: results-screen viewport coverage — assertion logic', () => {
  // PASS cases: position:fixed is always acceptable regardless of rect
  it('passes when position is fixed (correct implementation)', () => {
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'fixed',
      zIndex: '100',
      rectTop: 0,
      rectHeight: 844,
      coversViewport: true,
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, true);
    assert.equal(result.message, null);
  });

  it('passes when position is fixed even if rectTop is non-zero (off-screen fixed elements)', () => {
    // Some games use position:fixed but hide results off-screen initially
    // until needed. position:fixed itself satisfies the contract.
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'fixed',
      zIndex: '9999',
      rectTop: -1000,
      rectHeight: 844,
      coversViewport: false,
    });
    assert.equal(result.passes, true, 'position:fixed always passes regardless of rectTop');
  });

  it('passes when coversViewport is true even if position is not fixed (absolute-fill pattern)', () => {
    // Some games use position:absolute with 100vh height and top:0 — this also covers
    // the viewport and is acceptable (though position:fixed is preferred).
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'absolute',
      zIndex: '100',
      rectTop: 0,
      rectHeight: 844,
      coversViewport: true,
    });
    assert.equal(result.passes, true, 'coversViewport:true passes even without position:fixed');
  });

  // FAIL cases: the P0 pattern — position:static pushed off-viewport
  it('fails when position is static and screen is off-viewport (P0 bug pattern)', () => {
    // Exact values observed in quadratic-formula #546 and soh-cah-toa #544 audits
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'static',
      zIndex: 'auto',
      rectTop: 145, // Math.round(144.5)
      rectHeight: 300,
      coversViewport: false,
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, false);
    assert.ok(result.message.includes('position=static'), 'message shows position value');
    assert.ok(result.message.includes('top=145px'), 'message shows rectTop');
    assert.ok(result.message.includes('coversViewport=false'), 'message shows coversViewport');
  });

  it('fails when position is relative and screen does not cover viewport', () => {
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'relative',
      zIndex: '1',
      rectTop: 500,
      rectHeight: 200,
      coversViewport: false,
    });
    assert.equal(result.passes, false);
    assert.ok(result.message.includes('position=relative'));
    assert.ok(result.message.includes('top=500px'));
  });

  it('fails when position is sticky and screen does not cover viewport', () => {
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'sticky',
      zIndex: '10',
      rectTop: 200,
      rectHeight: 400,
      coversViewport: false,
    });
    assert.equal(result.passes, false);
    assert.ok(result.message.includes('position=sticky'));
  });

  // SKIP case: no results element found
  it('skips when results element is not found (game has no dedicated results element)', () => {
    const result = assertResultsViewportCoverage({ found: false });
    assert.equal(result.skipped, true);
    assert.equal(result.passes, undefined, 'no pass/fail when skipped');
  });

  // TE-RES-002: rectTop guard — false-pass prevention for scrolled-down relative screens
  it('fails when height >= innerHeight but rectTop=200px (scrolled below fold — coversViewport=false)', () => {
    // A position:relative element in a full-height flex parent may have height >= innerHeight
    // but be pushed 200px below the viewport origin. Without the rectTop guard, an older
    // coversViewport formula could incorrectly pass if it only checked height. Verifies the
    // guard is enforced: coversViewport must be false when rectTop=200 > 10.
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'relative',
      zIndex: 'auto',
      rectTop: 200,
      rectHeight: 667,
      coversViewport: false, // rectTop=200 > 10 — coversViewport correctly false
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, false, 'rectTop=200 must fail even when height covers viewport');
    assert.ok(result.message.includes('top=200px'), 'message shows scrolled-down rectTop');
  });

  it('passes when position:fixed and top=0 (standard fully-correct implementation)', () => {
    // Canonical case: gen prompt shipped position:fixed; inset:0; z-index:100
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'fixed',
      zIndex: '100',
      rectTop: 0,
      rectHeight: 844,
      coversViewport: true,
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, true, 'position:fixed with top=0 must pass');
    assert.equal(result.message, null);
  });

  it('passes when height >= innerHeight AND rectTop <= 10 (full-viewport relative with rectTop guard satisfied)', () => {
    // position:absolute/relative with 100vh height and top within 10px tolerance is acceptable
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'absolute',
      zIndex: '50',
      rectTop: 5,
      rectHeight: 844,
      coversViewport: true, // rectTop=5 <= 10 AND height=844 >= innerHeight
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, true, 'height >= innerHeight with rectTop=5 within tolerance must pass');
    assert.equal(result.message, null);
  });

  // CR-019: SKIP cases — element exists but not yet visible (display:none or zero-size)
  it('skips when element exists but display:none (results screen hidden before game ends)', () => {
    // page.evaluate() returns skipped:true when getComputedStyle(el).display === 'none'
    // This prevents false-positive assertion failure before the game reaches results phase
    const result = assertResultsViewportCoverage({ found: true, skipped: true, reason: 'element not visible yet' });
    assert.equal(result.skipped, true);
    assert.equal(result.passes, undefined, 'no pass/fail when element is display:none');
  });

  it('skips when element exists but has zero height AND zero width (not yet rendered)', () => {
    // page.evaluate() returns skipped:true when rect.height === 0 && rect.width === 0
    // Covers elements that exist in DOM but have not yet been shown (e.g. opacity:0 with no layout)
    const result = assertResultsViewportCoverage({ found: true, skipped: true, reason: 'element not visible yet' });
    assert.equal(result.skipped, true);
    assert.equal(result.passes, undefined, 'no pass/fail when element is zero-size');
  });

  // CR-019: FAIL case preserved — visible element with position:static still fails
  it('still fails when element is visible (display:block) but position:static off-viewport', () => {
    // When element IS visible (not skipped), existing assertion logic must still fire
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'static',
      zIndex: 'auto',
      rectTop: 145,
      rectHeight: 300,
      coversViewport: false,
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, false, 'visible position:static element still triggers failure');
    assert.ok(result.message.includes('position=static'), 'message includes position');
  });
});

// ─── coversViewport computation logic ────────────────────────────────────────
//
// These tests validate the coversViewport flag logic as it would be computed
// inside page.evaluate() in the browser.
// TE-RES-002: flag is: rect.top <= 10 && rect.height >= window.innerHeight
// The <= 10 guard (was <= 0) prevents false-pass when a position:relative
// element has height >= innerHeight but is scrolled below the fold (rectTop=200px).

describe('TE-RES-001: coversViewport flag computation', () => {
  function computeCoversViewport(rectTop, rectHeight, viewportHeight) {
    // Mirrors the page.evaluate() logic in lib/pipeline-test-gen.js (TE-RES-002)
    return rectTop <= 10 && rectHeight >= viewportHeight;
  }

  it('coversViewport is true when top=0 and height equals viewport height (iPhone SE: 667px)', () => {
    assert.equal(computeCoversViewport(0, 667, 667), true);
  });

  it('coversViewport is true when top=0 and height exceeds viewport height', () => {
    assert.equal(computeCoversViewport(0, 844, 667), true);
  });

  it('coversViewport is false when top > 0 (screen pushed down by flex-row parent)', () => {
    // The exact CDN body flex-row push observed in UI/UX audits
    assert.equal(computeCoversViewport(145, 667, 667), false);
  });

  it('coversViewport is false when height < viewportHeight (partial coverage)', () => {
    assert.equal(computeCoversViewport(0, 300, 667), false);
  });

  it('coversViewport is true when top is slightly negative (fixed element with top:-1px for hairline)', () => {
    assert.equal(computeCoversViewport(-1, 668, 667), true);
  });

  // TE-RES-002: rectTop guard boundary tests
  it('coversViewport is true when top=10 and height covers viewport (10px tolerance boundary)', () => {
    // Allows up to 10px of top offset — e.g. a 1px border or sub-pixel rounding
    assert.equal(computeCoversViewport(10, 667, 667), true);
  });

  it('coversViewport is false when top=11 and height covers viewport (just outside tolerance)', () => {
    // 11px > 10px tolerance — screen starts too far down, bottom of results would be off-fold
    assert.equal(computeCoversViewport(11, 667, 667), false);
  });
});

// ─── selector priority logic ──────────────────────────────────────────────────
//
// The page.evaluate() selector chain: data-phase="results" → #results-screen →
// .results-screen → [class*="results"]. This tests the priority expectation.

describe('TE-RES-001: selector priority documentation', () => {
  it('data-phase="results" selector is highest priority (from harness syncDOMState)', () => {
    // The harness sets data-phase="results" on #app when endGame('victory') is called.
    // Querying document.querySelector('[data-phase="results"]') finds the full-screen
    // results overlay, not #app itself, because #app has data-phase on it via attribute
    // and games typically have a child element with data-phase="results" for the results screen.
    // This is the most reliable selector — it reflects actual game state.
    assert.ok(true, 'data-phase selector is the primary selector in checkResultsScreenViewport()');
  });

  it('fallback selectors cover common naming conventions', () => {
    // Covers: #results-screen (most common), .results-screen, [class*="results"]
    const fallbackSel = '#results-screen, .results-screen, [class*="results"]';
    assert.ok(fallbackSel.includes('#results-screen'), 'covers ID-based selector');
    assert.ok(fallbackSel.includes('.results-screen'), 'covers class-based selector');
    assert.ok(fallbackSel.includes('[class*="results"]'), 'covers partial class match');
  });
});

// ─── error message format validation ─────────────────────────────────────────

describe('TE-RES-001: error message format', () => {
  it('error message includes all diagnostic values needed to debug', () => {
    const result = assertResultsViewportCoverage({
      found: true,
      position: 'static',
      zIndex: 'auto',
      rectTop: 145,
      rectHeight: 300,
      coversViewport: false,
    });
    assert.ok(!result.passes);
    // Must include all four diagnostic values
    assert.ok(result.message.includes('position='), 'message includes position key');
    assert.ok(result.message.includes('top='), 'message includes top key');
    assert.ok(result.message.includes('height='), 'message includes height key');
    assert.ok(result.message.includes('coversViewport='), 'message includes coversViewport key');
    // Must mention the requirement
    assert.ok(
      result.message.includes('position:fixed') || result.message.includes('full viewport'),
      'message states what is required',
    );
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Tests for the TransitionScreen content assertion (TE-TRANSITION-001)
//
// The P0 pattern: transitionScreen.show('victory', ...) called in string mode
// instead of object API — renders a blank white .mathai-transition-screen--active
// with no title, no score, and no Play Again button.
// (observed: which-ratio #561 UI/UX audit — blank victory screen, Play Again unreachable)
//
// The actual checkTransitionScreenContent() helper is injected into the shared
// Playwright boilerplate in lib/pipeline-test-gen.js and runs inside every
// generated game-flow spec file.
// ─────────────────────────────────────────────────────────────────────────────

// ─── Replicate the assertion logic from checkTransitionScreenContent() ────────
//
// Mirrors the page.evaluate() return shape and the assertion condition exactly
// as defined in the boilerplate in lib/pipeline-test-gen.js.
// Any change to one must be reflected in the other.

function assertTransitionScreenContent(contentCheck) {
  if (!contentCheck.found) {
    // Transition screen not active — skip
    return { skipped: true };
  }
  const passes = contentCheck.buttonCount > 0;
  return {
    skipped: false,
    passes,
    message: passes
      ? null
      : `Victory/results TransitionScreen must have at least 1 visible button. Got: ${JSON.stringify(contentCheck)}. Check transitionScreen.show() — must use object API with buttons array, not string mode.`,
  };
}

describe('TE-TRANSITION-001: TransitionScreen content — assertion logic', () => {
  // PASS case: active transition screen with visible button
  it('passes when active transition screen has at least 1 visible button', () => {
    const result = assertTransitionScreenContent({
      found: true,
      buttonCount: 1,
      hasTitle: true,
      titleText: 'Well done!',
      firstButtonText: 'Play Again',
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, true);
    assert.equal(result.message, null);
  });

  it('passes when active transition screen has multiple visible buttons', () => {
    const result = assertTransitionScreenContent({
      found: true,
      buttonCount: 2,
      hasTitle: true,
      titleText: 'Victory!',
      firstButtonText: 'Play Again',
    });
    assert.equal(result.passes, true);
  });

  // FAIL case: the P0 pattern — blank screen, 0 buttons (which-ratio #561)
  it('fails when active transition screen has 0 visible buttons (blank screen P0)', () => {
    // Exact pattern observed in which-ratio #561: transitionScreen.show('victory', ...)
    // called with string mode — screen activates but renders blank
    const result = assertTransitionScreenContent({
      found: true,
      buttonCount: 0,
      hasTitle: false,
      titleText: undefined,
      firstButtonText: undefined,
    });
    assert.equal(result.skipped, false);
    assert.equal(result.passes, false);
    assert.ok(result.message.includes('at least 1 visible button'), 'message states requirement');
    assert.ok(result.message.includes('buttonCount'), 'message includes buttonCount in diagnostic JSON');
    assert.ok(result.message.includes('object API'), 'message mentions correct API usage');
  });

  it('fails message includes full contentCheck payload for diagnostics', () => {
    const payload = {
      found: true,
      buttonCount: 0,
      hasTitle: false,
      titleText: undefined,
      firstButtonText: undefined,
    };
    const result = assertTransitionScreenContent(payload);
    assert.ok(!result.passes);
    // The message must embed the JSON payload so the failure is immediately actionable
    assert.ok(result.message.includes('"buttonCount":0'), 'message embeds buttonCount:0');
  });

  // SKIP case: transition slot exists but screen not active
  it('skips when transition screen is not active (found: false)', () => {
    const result = assertTransitionScreenContent({ found: false });
    assert.equal(result.skipped, true);
    assert.equal(result.passes, undefined, 'no pass/fail when skipped');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Tests for the canvas responsive overflow assertion (TE-CANVAS-001)
//
// The P0 pattern: canvas hardcoded at width="500" causes horizontal scroll on
// 375-480px mobile viewports (observed: right-triangle-area #543, UI-RTA-002).
//
// GEN-CANVAS-001 shipped to gen prompts (max-width:100%; height:auto) but
// computed layout requires browser rendering — static T1 checks cannot catch
// it at runtime. These tests validate the assertion logic by simulating the
// page.evaluate() return shape used in the Playwright boilerplate.
//
// The actual Playwright runtime version (with page.evaluate) is injected into
// the shared boilerplate in lib/pipeline-test-gen.js for canvas-based games.
// The exported checkCanvasResponsive() mirrors the same throw condition.
// ─────────────────────────────────────────────────────────────────────────────

const { checkCanvasResponsive } = require('../lib/pipeline-test-gen');

describe('TE-CANVAS-001: canvas responsive overflow — assertion logic', () => {
  // PASS case: canvas fits within viewport
  it('does not throw when canvas offsetWidth fits within viewport', () => {
    assert.doesNotThrow(() => {
      checkCanvasResponsive({ found: true, passed: true });
    }, 'canvas fits viewport — no error expected');
  });

  // PASS case: no canvas elements in the game
  it('does not throw when no canvas elements are present (found: false)', () => {
    assert.doesNotThrow(() => {
      checkCanvasResponsive({ found: false });
    }, 'no canvas — skip assertion, no error');
  });

  // FAIL case: the UI-RTA-002 pattern — canvas 500px on 375px viewport
  it('throws when canvas overflows viewport with diagnostic message including widths', () => {
    const payload = {
      found: true,
      passed: false,
      canvasWidths: [{ offsetWidth: 500, viewport: 375 }],
    };
    assert.throws(
      () => checkCanvasResponsive(payload),
      (err) => {
        assert.ok(err.message.includes('Canvas overflow'), 'message starts with Canvas overflow');
        assert.ok(err.message.includes('500'), 'message includes canvas offsetWidth');
        assert.ok(err.message.includes('375'), 'message includes viewport width');
        assert.ok(err.message.includes('GEN-CANVAS-001'), 'message includes rule tag');
        assert.ok(err.message.includes('max-width:100%'), 'message includes required CSS fix');
        return true;
      },
      'canvas 500px on 375px viewport must throw with diagnostic message',
    );
  });

  // FAIL case: multiple overflowing canvases
  it('throws when multiple canvases overflow viewport — all widths included in message', () => {
    const payload = {
      found: true,
      passed: false,
      canvasWidths: [
        { offsetWidth: 500, viewport: 375 },
        { offsetWidth: 480, viewport: 375 },
      ],
    };
    assert.throws(
      () => checkCanvasResponsive(payload),
      (err) => {
        assert.ok(err.message.includes('500'), 'first overflowing canvas width in message');
        assert.ok(err.message.includes('480'), 'second overflowing canvas width in message');
        return true;
      },
      'multiple overflowing canvases must all appear in the error message',
    );
  });

  // EDGE case: canvas exactly at viewport width — no overflow
  it('does not throw when canvas offsetWidth equals viewport width exactly (boundary)', () => {
    assert.doesNotThrow(() => {
      checkCanvasResponsive({ found: true, passed: true });
    }, 'canvas exactly at viewport width must not trigger overflow');
  });

  // Error message format validation
  it('error message includes all values needed to diagnose and fix the issue', () => {
    const payload = {
      found: true,
      passed: false,
      canvasWidths: [{ offsetWidth: 500, viewport: 480 }],
    };
    let caught;
    try {
      checkCanvasResponsive(payload);
    } catch (err) {
      caught = err;
    }
    assert.ok(caught, 'error must be thrown');
    assert.ok(caught.message.includes('offsetWidth'), 'message includes offsetWidth key');
    assert.ok(caught.message.includes('viewport'), 'message includes viewport key');
    assert.ok(caught.message.includes('GEN-CANVAS-001'), 'message includes rule tag for traceability');
    assert.ok(caught.message.includes('height:auto'), 'message includes height:auto CSS fix');
  });
});
